[versions]
compose = "2024.02.00"
hilt = "2.50"
room = "2.6.1"

[libraries]
androidx-compose-bom = { module = "androidx.compose:compose-bom", version.ref = "compose" }
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
hilt-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "hilt" }
room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
